### ISSUE TITLE
this package conflicts with other resource tools that modify the custom-index-toolbar component

### ISSUE THREAD

**Issue by vesper8** [gobrightspot/nova-detached-actions#9]
Hello,

Following up on the issues I described in https://github.com/gobrightspot/nova-detached-actions/pull/5

After some debugging and trying it out on a fresh install of Laravel / Nova I realized the problem was somewhere on my end and eventually figured it out.

I had previously managed to add custom buttons to the toolbar (next to create button) using the method I describe here https://github.com/laravel/nova-issues/issues/786#issuecomment-626251379

It's also thanks to posting this reply that I found out about your own package when someone else replied the next day

Anyway that method involves overriding the custom-index-toolbar component to allow the loading of resource-specific custom buttons.

Commenting this line and rebuilding my resource tool makes your buttons appear again (and breaks my custom tool):
```
Vue.component('custom-index-toolbar', require('./components/CustomIndexToolbar'));
```

Now I realize that this particular use-case where I needed to have a custom button display a modal with a form can 100% be replaced by the use of your package which is great and much simpler. However if you needed to do something more complex in that modal it may still be necessary to create a resource tool, or maybe it could be accomplished by creating custom fields.. I haven't run into a situation yet where I need to create a custom button that opens a modal in which there's something a custom field can't accomplish.

Anyway food for thought.. I suppose as of 1.0.4 you too have begun overriding the `custom-index-toolbar` component which is why I started having the issue.. this conflict may be avoidable? I'm not sure.. anyway feel free to close this : ) and thanks for your quick improvements!

**Comment by gobrightspot** [comment]
Actually, we've always been overriding the `CustomIndexToolbar` component, as of `v1.0.5` we started overriding the `CustomDetailToolbar` component too! 😊

There's a comment on [that same Nova issue thread](https://github.com/laravel/nova-issues/issues/786#issuecomment-427952057) that I've been storing in mind for a while now with a view to possibly adapting this approach, although I've yet to see anyone else do it in the wild.

The awkward part here is since there's no official way to add support for the functionality we want without overriding these components, unless every package adopts this approach to allow for a "faux interoperability" of sorts when overriding these components, it's all for naught anyway.

I'm going to leave this issue open for a while and look into adding the approach from the link above, I'll let you know if I can figure it out and actually confirm that another tool doing the same thing will work too.

Thanks for your interest and taking the time to test stuff out, it's a huge help in the early parts of getting this package out there!

**Comment by vesper8** [comment]
No problem : )

So.. if you were always overriding `CustomIndexToolbar`, then how come I only started experiencing the issue as of 1.0.4?

**Comment by gobrightspot** [comment]
In 1.0.4, we removed the `DetachedAction` Tool which depending on the order you registered your tools could have put our package before/after (whichever was necessary to override) yours.

**Comment by vesper8** [comment]
Ah I see, so probably my custom tool wasn't working anymore prior to 1.0.4 and I just hadn't noticed because I haven't tested it since

**Comment by gobrightspot** [comment]
Yep, that's my bet anyway.

**Comment by gobrightspot** [comment]
So, thinking a little more on this, in order to allow people to use the approach from the link above, we'd need to change our package `CustomIndexToolbar` component to include the resource 'tool' component defined, which would be defined in a custom resource tool, built by a developer. In order to do so, based on the recommendation in the thread, we would have our component check for the existence of a component named:`${this.resourceName}-index-toolbar` or if you have a `Users` resource, then `users-index-toolbar`.

Our package would assume that since you want to use our package to define the custom toolbar, then the developer wants their component to live alongside ours. Which means we would need to convert our `CustomIndexToolbar` component to something like`DetachedActionsIndex` component, and we would define it like `<detached-actions-index :resourceName="resourceName" />` - For example:

```vue
<template>
    <div class="w-full flex">
        <component v-if="hasComponent" :is="component" />
        <div class="flex w-full justify-end items-center mx-3">
            <detached-actions-index :resourceName="resourceName" />
        </div>
    </div>
</template>
<script>
  export default {
    props: ['resourceName'],
    computed: {
      component() {
        return `${this.resourceName}-index-toolbar`;
      },
      hasComponent() {
        return this.component in this.$options.components;
      }
    }
  }
</script>
```

This is actually kind of cool, it would mean a developer could create a custom resource tool, let's say they want to put a custom component on the User resource, they would just add something like within their `tool.js` file:

```js
import UsersIndexToolbar from './components/UsersIndexToolbar'

Nova.booting((Vue, router) => {
    Vue.component('users-index-toolbar', UsersIndexToolbar)
})
```

And create the component in `components/UserIndexToolbar` like so:

```vue
<template>
    <div class="w-full flex justify-end">
        <button class="btn btn-default btn-primary">
            Button
        </button>
    </div>
</template>
<script>
  export default {
    props: ['resource', 'resourceName', 'resourceId'],
    // do more stuff here
  }
</script>
```

I'm not sure it would work for every situation, in fact it most likely wouldn't but at least if someone really wanted to add some custom stuff, they could. So not 'interoperable' per se but customizable/overridable.

Any thoughts on this approach? The cool thing would be we could add this and it wouldn't break any existing functionality.

I've also created a branch if you want to try it out: https://github.com/gobrightspot/nova-detached-actions/tree/interoperable-custom-toolbars

**Comment by sanderbaas** [comment]
I had this issue with another nova package and solved it by using Vue.nextTick to register my own nova-component and from there call the 3rd party nova package.

This is the tool.js of my nova-component
```
Nova.booting((Vue, router, store) => {
    // register in nextTick, to prevent being overwritten by other packages
    Vue.nextTick(function(){
        Vue.component('custom-index-toolbar', require('./components/CustomIndexToolbar'));
        Vue.component('progress-data-index-toolbar', require('./components/ProgressDataIndexToolbar'));
        Vue.component('anaseqal-nova-import', require('../../../../vendor/anaseqal/nova-import/resources/js/components/CustomIndexToolbar'));
    });
})
```

And then in the CustomIndexToolbar
```
<template>
    <div class="flex w-full justify-end items-center mx-3">
        <component v-if="hasComponent" :is="component" />
        <anaseqal-nova-import class="anaseqal-nova-import"
          v-if="!viaResource"
          :resource-name="resourceName"
        />
    </div>
</template>

<script>
    export default {
        props: ['resourceName'],
        computed: {
            component(){
                return this.resourceName + '-index-toolbar';
            },
            hasComponent()
            {
                return this.component in this.$options.components;
            }    
        }
    }
</script>

<style scoped>
    .anaseqal-nova-import {
        width:auto;
        margin-right:0;
    }
</style>
```

**Comment by eoghanobrien** [comment]
Since this issue has been around awhile and has no community fux. I'm gonna close this out.
